project:
  type: website

website:
  title: "lectures"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: finmgmt.qmd
        text: Financial Management
      - href: finstrat.qmd
        text: Financial Strategy

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



