---
#title: "Risk and Return"
author: "Lucas S. Macoris"
format:
  revealjs:
    title: 'How to Ensure that Projects Truly Have Positive NPVs'
    theme: [default, custom.scss]
    auto-stretch: false
    author: 'Lucas S. Macoris'
    logo: logo.jpg
    footer: "[@ Website](https://lsmacoris.github.io/) | [@ Slides](https://lsmacoris.github.io/lectures/fin-mgmt.html) | [@ Office-hour appointments](https://calendly.com/lucas-macoris-fgv/appointment-lsm)"
    toc: false
    cls: abntex2.cls
    incremental: true
    bibliography: 'Bibliography.bib'
    slide-number: true
    show-slide-number: all
    transition: slide
    background-transition: fade
    chalkboard: true
    width: 1600
    height: 900
    smaller: false

editor: visual
from: markdown+emoji
---

## Ensuring Truly Positive NPVs

-   In the last lecture, you saw how the choice of assumptions may severely change our NPV estimates

-   How to ensure that the NPV you're measuring is really [positive]{.green}?

-   Some areas to consider

    1.  Behavioral Biases
    2.  Avoiding Forecast Errors
    3.  Identifying Competitive Advantage

. . .

$\rightarrow$ *For this lecture, refer to* [@BMA]

## Behavioral Biases

-   Senior management needs to be closely involved in strategic investment decisions, but it must rely heavily on information that is provided by project proposers

-   Information providers may have incentives to exacerbate assumptions:

    1.  Optimism bias

    <!-- -->

    a.  Entrepreneurs tend to overestimate the likelihood of success, although the survival rate of start-up firms is generally low
    b.  They also tend to keep their "pet-projects" - *i.e*, projects that they assign a much higher success probability than what it actually is

    <!-- -->

    2.  Overconfidence bias

    <!-- -->

    a.  Project managers tend to overestimate ["success"]{.green} scenarios and underestimate ["fail"]{.red} ones
    b.  Not considering worst-case scenarios may hinder investors to understand the real NPV

## Avoiding Forecast Errors

-   Suppose you have your project sponsors to give you [honest]{.blue} forecasts

-   They are unbiased: on average, the error will be zero

-   What about the deviations from it? As a manager, you can't be expected to check every cash-flow forecast, but you can ask some questions to ensure that each project really does have a positive NPV

-   How can you "gut-check" the estimates before diving into each single assumption? Whenever available, look at market values

    1.  Many capital assets are traded in a competitive market, so it makes sense to start with the market price and then ask why you can earn more than your rivals from these assets

    2.  Stocks, for example, have both public and private information embedded on their values. Investors have already evaluated the information that is generally known. Security analysts do not need to evaluate this information again, and can concentrate on their private information

## Keeping Competitive Advantage

-   What does a positive *NPV* metric tells us, in reality? It means that a given investment earns [more]{.green} than it should after factoring its risk

-   **Question**: if that is the case, then can we assert that no one else is going to pursue the same project? A couple of thoughts:

    1.  *NPV* goes hand in hand with economic profits. As markets become more competitive, economic rents go down, and so does NPV
    2.  In a perfect equilibrium, an investment should earn zero NPV - *i.e*, it would yield only the value that compensates its risks, but no economic rents

-   That leaves us with another question: if a given project is actually a [positive]{.green} NPV one, which factors [sustain]{.blue} such economic rents so that other players do not erode it?

-   A [competitive advantage]{.blue} will protect a firm only if it is durable and can be sustained against competition from other businesses!

## Example: the *AI* race

-   After the widespread diffusion of *OpenAI'*s ChatGPT, there has been an arms race for the dominance of the artificial intelligence (AI) market

-   When you look at how investors value the big-tech firms, no other firm has benefited from the boom in artificial intelligence as much as *Nvidia* (ticker: *NVDA*)!

-   Why? We do have big competitors, such as *AMZ*, *MSFT*, *GOOGL*, as well as other newborns, such as *OpenAI* and *Anthropic*

    1.  *NVDIA*'s competitive advantage in the market, at least seem by the lens of the investors, makes them assign a high probability of success to its projects

    2.  As a consequence, stock prices surged more than any other publicly-traded firm in the AI race

. . .

$\rightarrow$ Suggested Reading: [Why do Nvidia's chips dominate the AI market?](https://www.economist.com/the-economist-explains/2024/02/27/why-do-nvidias-chips-dominate-the-ai-market?utm_medium=cpc.adword.pd&utm_source=google&ppccampaignID=19495686130&ppcadID=&utm_campaign=a.22brand_pmax&utm_content=conversion.direct-response.anonymous&gad_source=1&gclid=CjwKCAjwxLKxBhA7EiwAXO0R0FyLvGBMotJqvjewnQYweJ-kvWu-OClwb9bbO3S97TzfuuzngVBFVxoCKNgQAvD_BwE&gclsrc=aw.ds)

## Example: the *AI* race

```{r,fig.align='center',fig.height=8,fig.width=16}
library(highcharter)
library(quantmod)

x <- getSymbols("GOOG", auto.assign = FALSE)
y <- getSymbols("AMZN", auto.assign = FALSE)
z <- getSymbols("NVDA", auto.assign = FALSE)
k <- getSymbols("MSFT", auto.assign = FALSE)

highchart(type = "stock") %>% 
  hc_add_series(x,type='line') %>% 
  hc_add_series(y,type='line') %>%
  hc_add_series(k,type='line') %>%
  hc_add_series(z,type='line') %>%
  hc_xAxis(title = list(style=list(fontSize= '15px')),
           labels = list(style=list(fontSize= '15px'))) %>%
  hc_yAxis(title = list(style=list(fontSize= '15px')),
           labels = list(style=list(fontSize= '15px')))

```

## Wrapping-up

-   Positive NPV projects should be accompanied with clear competitive advantage rationales:
    1.  If your project does not have a clear competitive advantage, how you can then justify that economic profits would not erode over time?
    2.  What makes your investment/project so special in such a way that other firms cannot easily replicate the same investment project?
-   These questions help us as investors to think beyond simply math and scenario simulation, and think more thoroughly about the factors that justify the assumptions used in our free cash-flow models

## References
