---
#title: "Risk and Return"
author: "Lucas S. Macoris"
format:
  revealjs:
    title: 'Long-Term Financing through Debt '
    theme: [default, custom.scss]
    auto-stretch: false
    author: 'Lucas S. Macoris'
    logo: logo.jpg
    footer: "[@ Website](https://lsmacoris.github.io/) | [@ Slides](https://lsmacoris.github.io/lectures) | [@ Office-hour appointments](https://calendly.com/lucas-macoris-fgv/appointment-lsm)"
    toc: false
    cls: abntex2.cls
    incremental: true
    bibliography: 'Bibliography.bib'
    slide-number: true
    show-slide-number: all
    transition: slide
    background-transition: fade
    chalkboard: true
    width: 1600
    height: 900
    smaller: false
    
editor: visual
from: markdown+emoji
---

## Outline

-   This lecture is mainly based the following textbooks:

    1.  [@BDM]
    2.  [@BMA]

-   Study review and practice: I strongly recommend using [Prof. Henrique Castro](https://henriquemartins.net/) (FGV-EAESP) materials. Below you can find the links to the corresponding exercises related to this lecture:

    1.  Multiple Choice Exercises - click [here](https://henriquemartins.net/teaching/financial_strategy/p6tf.html)

. . .

$\rightarrow$ *For coding replications, whenever applicable, please follow [this](https://lsmacoris.github.io/lectures/fin-strat.html) page or hover on the specific slides with coding chunks.*

## Raising long-term money through debt financing

-   Firms can also depart from the choice of issuing equity and instead fund heir long-term investment opportunities through *debt financing*

-   In this chapter, we'll see discuss some specific types of debt:

    1.  Public Debt
    2.  Private Debt

-   Each type of debt has its own specific settings, and it is important to bear in mind characteristics such as the presence of covenants, the importance of ratings, and the eventual situation of repayment provisions

## Public Debt

-   One way that a firm can raise capital through through debt financing is through the issuance of [Public Debt]{.blue}:

    1.  It refers to Corporate Bonds issued by corporations
    2.  They account for a significant amount of invested capital in the U.S.

-   A key distinction of Public Debt is the fact that it a *tradable* security in a public market

-   Due to its nature, whenever a firm has interest issuing Public Debt, it must follow a *Prospectus* (similar to the IPO case). In addition to that, the prospectus must include an indenture, a formal contract between the bond issuer and a trust company. The trust company represents the bondholders and makes sure that the terms of the indenture are enforced

-   In the case of default, the trust company represents the bondholders’ interests

. . .

$\rightarrow$ *Examples*: Bonds, Notes, Debentures

## Types of Corporate Debt

-   Historically, corporate bonds have been issued with a wide range of maturities:

    1.  Most corporate bonds have maturities of 30 years or less...
    2.  ... although in the past there have been original maturities of up to 999 years (*"perpetual bonds"*)

-   The *face value* or principal amount of the bond is denominated in standard increments, most often \$1,000

-   There are several types of Corporate Debt that can be publicly issued - in what follows, we'll look at the most important ones and its their characteristics

## Unsecured Debt

-   [Unsecured Debt]{.blue} is type of corporate debt that, in the event of bankruptcy, gives bondholders a claim to only the assets of the firm that are not already pledged as collateral on other debt. Examples include:

    1.  [Notes]{.blue}: notes typically are coupon bonds with maturities shorter than 10 years.
    2.  [Debentures]{.blue}: typically have longer maturities than notes.

-   In general, *Notes* and/or *Debentures* are used to finance [long-term]{.blue} investment opportunities

## Secured Debt

-   As opposed to Unsecured Debt, [Secured Debt]{.blue} is a type of corporate debt in which *specific assets* are pledged as [collateral]{.blue}. Examples include:

    1.  [Mortgage Bonds]{.blue}: Real property is pledged as collateral that bondholders have a direct claim to in the event of bankruptcy. They are paid with the cash flow source generated by the asset

    2.  [Asset-Backed Bonds (ABS)]{.blue}: specific assets are pledged as collateral that bondholders have a direct claim to in case of bankruptcy. Can be any kind of asset that a firm owns

. . .

$\rightarrow$ *Asset-backed securities (ABS) played a key role in the 2008 sub-prime financial crisis. Among other effects, the fact that any asset can be pledged as collateral can create issues if there are widespread distortions in the market value of these assets*

## Corporate Debt - Terms and Characteristics

-   Public Debt can vary significantly in terms of offer characteristics - the most important are:

1.  [Tranches]{.blue}: different classes of securities that comprise a single bond issue - it helps creating different offers for bond investors

2.  [Seniority]{.blue}: a bondholder’s priority in claiming assets not already securing other debt. Most debenture issues contain covenants restricting the company from issuing new debt with equal or higher priority than existing debt

-   *Subordinated Debentures*: Debt that, in the event of a default, has a lower priority claim to the firm’s assets than other outstanding debt
-   *Senior Debentures*: Debt that, in the event of a default, has a higher priority claim to the firm’s assets than other outstanding debt

4.  [Issuance Type]{.blue}: Domestic *versus* Foreign

## Private Debt

-   As opposed to Public Debt, Private Debt is a type of financing that is *not* publicly traded

    1.  The private debt market is larger than the public debt market...
    2.  ... and it has the advantage that it avoids the cost of registration but on the investor side has the disadvantage of being illiquid

-   The most common examples are *Loans*:

    1.  *Syndicated Bank Loan*: A single loan that is funded by a group of banks rather than just a single bank
    2.  *Line of Credit*: A credit commitment for a specific time period, typically two to three years, which a company can use as needed
    3.  *Private Placements*: A bond issue that is sold to a small group of investors rather than the general public. Because a private placement does not need to be registered, it is less costly to issue than public debt

## Bond Covenants

-   **Question:** how can debtholders constrain actions that might deviate from their interests?

. . .

::: nonincremental
::: callout-tip
### Definition

-   [Covenants]{.blue} are restrictive clauses in a bond contract that limit the issuers from undercutting their ability to repay the bonds. As a common feature in bonds, they may, for example:

1.  Restrict the ability of management to pay dividends
2.  Restrict the level of further indebtedness
3.  Specify that the issuer must maintain a minimum amount of working capital
:::
:::

1.  [Positive]{.green} Covenants: the firm must do something (keep specific financial ratios, pay taxes and other obligations, among others

2.  [Negative]{.red} Covenants: the firm must not do something (sell specific assets, pay too much dividend, among others

## Repayment Provisions

-   A bond issuer typically repays its bonds by making coupon and principal payments as specified in the bond contract. However, the issuer of the bond has other options to repay:

    1.  Repurchase a *fraction* of the outstanding bonds in the market
    2.  Make a tender offer for the entire issue
    3.  Exercise a call provision

- It may be optimal for bond issuers to repay bonds to optimize funding costs if, for example, interest rates have fallen (and the firm can refinance at a lower rate)

- In what follows, we'll see three different ways that a firm can repay its bond ahead of time

## Repayment Option #1: *Callable Bonds*

-   Bonds that contain a call provision that allows the issuer to repurchase the bonds at a predetermined price

-   It allows the issuer of the bond the right (but not the obligation) to retire all outstanding bonds on (or after) a specific date, for the *call* price. The *call* price is generally set at or above, and expressed as a % of face value (*e.g.*, 102% of face value)

-   Why an issuer might be interested in this option?

    1.  A firm may choose to call a bond issue if interest rates have fallen
    2.  The issuer can lower its borrowing costs by exercising the call on the callable bond and then immediately refinancing the issue at a lower rate

## Repayment Option #1: *Callable Bonds*, continued

-   Holders of callable bonds understand that the issuer will exercise the call option only when the coupon rate of the bond exceeds the prevailing market rate
-   If a bond is called, investors must reinvest the proceeds when market rates are lower than the coupon rate they are currently receiving
-   This makes callable bonds relatively less attractive to bondholders than identical non-callable bonds
-   A callable bond will trade at a lower price (and therefore a higher yield) than an otherwise equivalent non-callable bond

. . .

$\rightarrow$ *If the call provision offers a cheaper way to retire the bonds, however, the issuer will forgo the option of purchasing the bonds in the open market and call the bonds instead*

## *Callable Bonds*, Exercise

*IBM has just issued a callable (at par) five-year, $\small8\%$ coupon bond with annual coupon payments. The bond can be called at par in one year or anytime thereafter on a coupon payment date. It has a price of $\small$103$ per $\small$100$ face value. What is the bond’s yield to maturity and yield to call?*

. . .

$\rightarrow$ *Solution*: to calculate the YTM *yield-to-maturity*, we find $\small i$ such that the following equation is zero:

$$
\small -103+\sum_{t=1}^{4}\dfrac{8}{(1+i)^t}+\dfrac{108}{(1+i)^5}=0\rightarrow i=7.26\%
$$

On the other hand, the *yield-to-call* is calculated by finding $\small i$ such that the bond is called at the first available opportunity:

$$
\small -103+\dfrac{108}{(1+i)}=0\rightarrow i=4.85\%
$$

## Repayment Option #2: *Sinking Fund*

-   A method of repaying a bond in which a company makes regular payments into a fund administered by a trustee over the life of the bond. These payments are then used to repurchase bonds

-   This allows the firm to retire some of the outstanding debt without affecting the cash flows of the remaining bonds

-   The trust can either repurchase the bonds in the market (if the price is below the face value) or by lottery at the par (if the price is above face value)


## Repayment Option #3: Convertible Bond

-   A corporate bond with a provision that gives the bondholder an option to convert each bond owned into a fixed number of shares of common stock.

1.  [Conversion Ratio]{.blue}: The number of shares received upon conversion of a convertible bond, usually stated per $\small\$1,000$ of face value

2.  [Conversion Price]{.blue}: The face value of a convertible bond divided by the number of shares received if the bond is converted

. . .

**Example**: assume a convertible bond with a $\small\$1,000$ face value and a conversion ratio of $\small 15$. You have the following options: 1. If you convert the bond into stock, you will receive $\small15$ shares 2. If you do not convert, you will receive $\small\$1,000$

-   By converting, you essentially “pay” $\small \$1,000$ for $\small15$ shares, implying a price per share of $\small \$66.67$
-   If the price of the stock exceeds $\small \$66.67$, you will choose to convert; otherwise, you will take the cash

## Practice

-   Take a look at an example of a Debenture Prospectus for *Raízen S.A* - access [here](https://api.mziq.com/mzfilemanager/v2/d/c016735f-1711-48ce-919f-a8c701b83c19/89c9ee68-cdbd-42ea-07cd-71fd0a5f5e49?origin=1)

. . .

::: callout-important
::: nonincremental
[Practice using the following links:]{.big}

1.  [Multiple-choice Questions](https://henriquemartins.net/teaching/financial_strategy/p6tf.html){preview-link="true"}
:::
:::

# Appendix

## Other Types of Debt

-   [Sovereign Debt]{.blue}: Debt issued by national governments. U.S. Treasury securities represents the single largest sector of the U.S. bond market. The same is true un Brazil.

-   [Municipal Bonds (*Munis*)]{.blue}: not common in Brazil, these bonds are issued by state and local governments

-   [Asset-Backed Securities (ABS)]{.blue}: securities made up of other financial securities. Security’s cash flows come from the cash flows of the underlying financial securities that “back” it. This piece was in the center of the 2008 financial crisis

## References
